<?php
if (!defined('ABSPATH')) { exit; }
$category = get_query_var('frn_catalog');
$is_meat = $category === 'carne';
$title = $is_meat ? 'Carne' : 'Pescado y marisco';
$products = (new FRN_Catalog_Repository())->all($category);
$whatsapp = preg_replace('/\D+/', '', (string)get_option('frn_sp_whatsapp_number', '34624354950'));
$updated = $products ? mysql2date('d · m · Y', $products[0]['published_at']) : '';
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo esc_html($title); ?> · Stock y precios FRN Atlántico</title><?php wp_head(); ?></head><body class="frn-catalog-body"><header class="frn-top"><a href="<?php echo esc_url(home_url('/')); ?>" class="frn-brand"><strong>FRN</strong><span>ATLÁNTICO</span></a><nav><a href="<?php echo esc_url(home_url('/stock/pescado-marisco/')); ?>">Pescado / Marisco</a><a href="<?php echo esc_url(home_url('/stock/carne/')); ?>">Carne</a></nav></header><main><section class="frn-hero"><p>Stock profesional · España</p><h1><?php echo esc_html($title); ?></h1><div><span>Disponibilidad actualizada</span><strong><?php echo esc_html($updated ?: 'Pendiente de publicación'); ?></strong></div></section><section class="frn-catalog"><div class="frn-heading"><div><p>Catálogo comercial</p><h2>Stock + precio real</h2></div><input type="search" id="frn-search" placeholder="Buscar producto o marca…" aria-label="Buscar producto o marca"></div><div class="frn-table-wrap"><table id="frn-products"><thead><tr><th>Producto</th><th>Marca</th><th>Stock</th><th>Precio</th><th></th></tr></thead><tbody><?php if (!$products) : ?><tr><td colspan="5">El catálogo está preparado. Publica el primer Excel desde WordPress para mostrar stock y precios.</td></tr><?php else : foreach ($products as $product) : $message = sprintf('Hola FRN Atlántico, quiero consultar una condición especial para %s%s.', $product['product_name'], $product['product_code'] ? ' (' . $product['product_code'] . ')' : ''); ?><tr data-search="<?php echo esc_attr(strtolower($product['brand'] . ' ' . $product['product_name'] . ' ' . $product['product_code'])); ?>"><td><?php if ((int)$product['featured']) : ?><span class="frn-offer">Oferta</span><?php endif; ?><strong><?php echo esc_html($product['product_name']); ?></strong><small><?php echo esc_html($product['product_code']); ?></small></td><td><?php echo esc_html($product['brand']); ?></td><td><?php echo esc_html(number_format_i18n((float)$product['stock_kg'], 2)); ?> kg</td><td><?php echo $product['price_kg'] === null ? 'Consultar' : esc_html(number_format_i18n((float)$product['price_kg'], 2)) . ' €/kg'; ?></td><td><a class="frn-wa" href="https://wa.me/<?php echo esc_attr($whatsapp); ?>?text=<?php echo rawurlencode($message); ?>" target="_blank" rel="noopener">Consultar condición especial</a></td></tr><?php endforeach; endif; ?></tbody></table></div><p class="frn-terms">Stock sujeto a disponibilidad en el momento de confirmación. Precios y condiciones sujetos a validación comercial.</p></section></main><footer class="frn-footer"><span>FRN Atlántico</span><a href="<?php echo esc_url(home_url('/')); ?>">Volver a frnatlantico.es</a></footer><?php wp_footer(); ?></body></html>
